'use strict';
(() => {
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>Array.from(root.querySelectorAll(q));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='trace.keynote.notes.v1';
const params=new URLSearchParams(location.search), isPresenter=params.get('presenter')==='1';
const unique=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2,9);
let session=params.get('session')||unique();
try{if(!isPresenter){session=sessionStorage.getItem('trace.keynote.session')||session;sessionStorage.setItem('trace.keynote.session',session);}}catch{}
session=session.replace(/[^a-zA-Z0-9-]/g,'').slice(0,70);
const channelKey='trace.keynote.channel.'+session;
const ownId=unique();
let channel=null;
try{if('BroadcastChannel' in window)channel=new BroadcastChannel(channelKey);}catch{}
let index=0, mode='full', returnIndex=null, covered=false, modalType=null, lastFocus=null, toastTimeout=0;
let timerRunning=false, timerElapsed=0, timerStarted=0, lastSync=0, qaCategory='전체', qaQuery='', selectedAnswer=null, qaMatches=[];
let lastWheel=0, pointerStart=null, memoryNotes=[];
const briefPath=SLIDES.map((s,i)=>s.short?i:-1).filter(i=>i>=0);
const path=()=>mode==='brief'?briefPath:SLIDES.map((_,i)=>i);
HEADS.forEach((h,i)=>QA.push({id:'head-'+i,category:'기술',q:h[1]+' — 어떤 의미를 판단하나요?',keys:h[0]+' '+h[1]+' 14 head 의미 계약',short:HEAD_DETAILS[i],detail:['native head: '+h[0]+'. 이 설명은 보관 문서의 의미 계약을 회수한 것이며, 모든 경계 사례의 최종 라벨을 확정한 실행 schema는 아닙니다.','현재 모델의 registry, class order, applicability와 함께 확인해야 합니다. 의미 head는 정책 행동이나 거래 완료를 직접 반환하지 않습니다.'],caution:'해당 head의 정확도가 검증됐다는 뜻은 아닙니다. 정상·위험·적용 불가 사례를 각각 평가해야 합니다.',slide:'semantics',evidence:'14-head 의미 계약 · 2026.09.29 문서'}));
function notify(message){clearTimeout(toastTimeout);$('#toast').textContent=message;$('#toast').classList.add('visible');toastTimeout=setTimeout(()=>$('#toast').classList.remove('visible'),3400);}
function post(payload){const data={...payload,from:ownId,role:isPresenter?'presenter':'audience',time:Date.now()};try{if(channel)channel.postMessage(data);else{localStorage.setItem(channelKey,JSON.stringify(data));localStorage.removeItem(channelKey);}}catch{if(isPresenter)notify('창 연결을 사용할 수 없습니다. 발표 화면에서 직접 조작해 주세요.');}}
function elapsed(){return timerElapsed+(timerRunning?Date.now()-timerStarted:0);}
function formatTime(ms){const t=Math.max(0,Math.floor(ms/1000));return String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');}
function sendState(){if(!isPresenter)post({type:'state',index,mode,returnIndex,covered,timerRunning,timerElapsed,timerStarted});}
function receive(data){if(!data||data.from===ownId)return;if(data.type==='request'&&!isPresenter)sendState();if(data.type==='command'&&!isPresenter)command(data.name,data.value,true);if(data.type==='state'&&isPresenter){index=Math.max(0,Math.min(SLIDES.length-1,Number(data.index)||0));mode=data.mode==='brief'?'brief':'full';returnIndex=data.returnIndex;covered=!!data.covered;timerRunning=!!data.timerRunning;timerElapsed=Number(data.timerElapsed)||0;timerStarted=Number(data.timerStarted)||0;lastSync=Date.now();renderPresenter();updateClock();}}
if(channel)channel.onmessage=e=>receive(e.data);
window.addEventListener('storage',e=>{if(e.key===channelKey&&e.newValue){try{receive(JSON.parse(e.newValue));}catch{}}if(e.key===STORE&&modalType==='notes')renderNotesList();});
function command(name,value,remote=false){if(isPresenter&&!remote){post({type:'command',name,value});if(Date.now()-lastSync>7000)notify('발표 화면을 함께 열어야 조작이 전달됩니다.');return;}if(name==='next')move(1);else if(name==='previous')move(-1);else if(name==='goto')goTo(value,{detour:true});else if(name==='timer')toggleTimer();else if(name==='resetTimer'){timerRunning=false;timerElapsed=0;timerStarted=0;updateClock();sendState();}else if(name==='cover')toggleCover();else if(name==='return')returnToTalk();}
function renderScenes(){const stage=$('#stage');stage.innerHTML=SLIDES.map((s,i)=>`<section class="scene ${s.id==='closing'?'closing':''}" id="scene-${s.id}" data-index="${i}" aria-label="${i+1}. ${esc(s.label)}" aria-hidden="true" inert><div class="scene-top"><span class="scene-label">${esc(s.chapter)}</span><span class="scene-num">${String(i+1).padStart(2,'0')} / ${SLIDES.length}</span></div><div class="scene-content">${s.html}</div><div class="scene-foot"><span>${esc(s.foot)}</span><span class="evidence-tag">${esc(s.source)}</span><button class="more" data-qa="${s.qa}">더 깊이 보기 ${icon('right')}</button></div></section>`).join('');updateScenario('planned');updateContext('request');}
function fit(){if(isPresenter)return;const area=$('#stage-area'),portrait=matchMedia('(max-width:650px) and (orientation:portrait)').matches;const scale=portrait?1:Math.min(area.clientWidth/1440,area.clientHeight/810);document.documentElement.style.setProperty('--scale',scale);}
function currentRouteIndex(){return path().indexOf(index);}
function renderRail(){const route=path();$('#chapter-rail').innerHTML=route.map((n,i)=>`<button class="chapter-tick ${n===index?'current':i<route.indexOf(index)?'past':''}" data-goto="${n}" aria-label="${n+1}. ${esc(SLIDES[n].label)}" ${n===index?'aria-current="step"':''} title="${n+1}. ${esc(SLIDES[n].label)}"></button>`).join('');$('#page-counter').innerHTML=String(index+1).padStart(2,'0')+' <span>/ '+SLIDES.length+'</span>';$('#current-title').textContent=SLIDES[index].label;$('#mode').value=mode;$('#previous').disabled=currentRouteIndex()===0||index===0;$('#next').disabled=currentRouteIndex()===route.length-1||index===SLIDES.length-1;$('#back-to-talk').classList.toggle('visible',returnIndex!==null&&returnIndex!==index);}
function goTo(n,{detour=false,hash=true,initial=false}={}){n=Number(n);if(!Number.isInteger(n)||n<0||n>=SLIDES.length)return;if(isPresenter){command('goto',n);return;}if(detour&&n!==index&&returnIndex===null)returnIndex=index;const old=$('.scene.active');if(old){old.classList.remove('active');old.setAttribute('aria-hidden','true');old.inert=true;}index=n;const next=$('#scene-'+SLIDES[index].id);next.classList.add('active');next.setAttribute('aria-hidden','false');next.inert=false;next.scrollTop=0;renderRail();if(hash){try{history.replaceState(null,'','#'+SLIDES[index].id);}catch{}}document.title='TRACE — '+SLIDES[index].label;$('#announce').textContent=(index+1)+' / '+SLIDES.length+' · '+SLIDES[index].label;fit();sendState();if(!initial&&!matchMedia('(prefers-reduced-motion:reduce)').matches){next.animate([{opacity:.35,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,easing:'cubic-bezier(.22,1,.36,1)'});}}
function move(direction){const route=path(),pos=route.indexOf(index);let target;if(pos<0)target=direction>0?route.find(n=>n>index):[...route].reverse().find(n=>n<index);else target=route[pos+direction];if(target!==undefined)goTo(target);}
function returnToTalk(){if(isPresenter){command('return');return;}if(returnIndex!==null){const n=returnIndex;returnIndex=null;goTo(n);}}
function toggleTimer(){if(timerRunning){timerElapsed=elapsed();timerRunning=false;}else{timerStarted=Date.now();timerRunning=true;}updateClock();sendState();}
function updateClock(){const label=formatTime(elapsed());$('#clock').textContent=label;$('#p-clock').textContent=label;$('#timer-symbol').innerHTML=icon(timerRunning?'pause':'play');$('#timer-toggle').setAttribute('aria-label',timerRunning?'타이머 일시정지':'타이머 시작');if(isPresenter){$('#p-status').textContent=Date.now()-lastSync<6000?'발표 화면 연결됨 · 이 창은 관객 화면에 표시되지 않습니다.':'발표 화면과 연결되지 않았습니다. 원래 발표 탭을 열어 두세요.';}}
function toggleCover(force){covered=typeof force==='boolean'?force:!covered;$('#screen-cover').classList.toggle('active',covered);if(covered)$('#screen-cover').focus();sendState();}
function updateScenario(key){const s=SCENARIOS[key]||SCENARIOS.planned;$('#scenario-quote').innerHTML=s.quote;$('#scenario-role').textContent=s.role;$('#scenario-signals').innerHTML=s.signals.map(row=>`<div class="signal-row"><span>${esc(row[0])}</span>${esc(row[1])}</div>`).join('');$('#scenario-action').textContent=s.action;$('#scenario-action').classList.toggle('accent',key==='coerced');$('#scenario-description').innerHTML=s.description;$$('[data-scenario]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===key)));if(!matchMedia('(prefers-reduced-motion:reduce)').matches)$('#scenario-card').animate([{opacity:.5,transform:'translateY(5px)'},{opacity:1,transform:'none'}],{duration:320,easing:'ease-out'});}
function updateContext(key){const education=key==='education';$('#context-setting').textContent=education?'금융사기 예방 교육 자료를 읽는 상황':'상대가 지금 계좌 이동을 요구하는 상황';$('#context-role').textContent=education?'CONTEXT':'EXTERNAL';$('#context-text').textContent=education?'“안전 계좌로 보내라”는 요구는 의심해야 합니다.':'지금 안전 계좌로 돈을 옮기세요.';$('#context-verdict').innerHTML=education?'<b>위험 문구의 인용 ≠ 현재 실행 지시</b>표현이 아니라 그 표현의 역할을 구분해야 합니다.':'<b>현재의 금융 행동을 요구하는 문맥</b>요청의 근거·주체·원래 의도와의 관계를 확인합니다.';$$('[data-context]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.context===key)));}
function header(title,sub='',extra=''){return `<div class="dialog-header"><div><h2 id="dialog-title">${esc(title)}</h2>${sub?'<p class="dialog-subtitle">'+esc(sub)+'</p>':''}</div><div style="display:flex;gap:8px;align-items:center">${extra}<button class="icon-btn dialog-close" data-close aria-label="닫고 발표로 돌아가기">${icon('close')}</button></div></div>`;}
function openDialog(type,markup,cls=''){const overlay=$('#overlay');if(overlay.hidden)lastFocus=document.activeElement;modalType=type;$('#dialog').className='dialog '+cls;$('#dialog').innerHTML=markup;overlay.hidden=false;$('#audience').inert=true;$('#presenter-root').inert=true;requestAnimationFrame(()=>{const el=$('input,textarea,button,a[href]', $('#dialog'));el?.focus();});}
function closeDialog(){if($('#overlay').hidden)return;$('#overlay').hidden=true;$('#audience').inert=false;$('#presenter-root').inert=false;modalType=null;if(lastFocus?.isConnected&&!lastFocus.closest('[inert]'))lastFocus.focus();else (isPresenter?$('#presenter-root'):$('#next')).focus();}
function normalize(s){return String(s).normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
const aliases={'몇퍼':'정확도','백퍼':'정확도','백프로':'정확도','백퍼센트':'정확도','일렉트라':'electra','개인정보':'privacy','헛소리':'한계','과적합':'일반화','양자화':'quantization','차별':'차별성'};
function rank(q,item){if(!q.trim())return 1;const nq=normalize(q),tight=nq.replace(/\s/g,''),title=normalize(item.q),body=normalize(item.keys+' '+item.short+' '+item.detail.join(' '));let score=0;if(title.replace(/\s/g,'').includes(tight))score+=50;if(body.replace(/\s/g,'').includes(tight))score+=18;const tokens=nq.split(' ').filter(t=>t.length>1&&!['어떻게','무엇인가요','인가요','있나요','하나요','설명해주세요','설명해줘','대해서','주세요','얼마나','현재','무슨'].includes(t));for(const t0 of tokens){const t=aliases[t0]||t0;if(title.includes(t))score+=10;if(normalize(item.keys).includes(t))score+=8;if(body.includes(t))score+=2;for(const k of Object.keys(aliases)){if(t0.includes(k)&&normalize(item.keys+' '+item.q).includes(aliases[k]))score+=7;}}return score;}
function showQA(id=null){qaCategory='전체';qaQuery='';selectedAnswer=id;const cats=['전체','제품','기술','AI·학습','검증','보안','도입'];openDialog('qa',header('질문을, 근거까지.',QA.length+'개 답변 · 로컬 검색 · 등록되지 않은 답변은 생성하지 않습니다.')+`<div class="qa-search">${icon('search')}<input id="qa-input" type="search" autocomplete="off" spellcheck="false" aria-label="질문 검색" placeholder="정확도, 은행 연동, 개인정보, 양자화…"><span class="key">Esc</span></div><nav class="qa-tabs" aria-label="질문 분류">${cats.map(c=>`<button data-category="${c}" class="${c==='전체'?'active':''}">${c}</button>`).join('')}</nav><div class="qa-main"><div class="qa-results" id="qa-results" aria-label="검색 결과"></div><article class="qa-answer" id="qa-answer" tabindex="-1" aria-label="선택한 질문의 답변"></article></div>`,'qa-dialog');$('#qa-input').addEventListener('input',e=>{qaQuery=e.target.value;selectedAnswer=null;renderQA();});renderQA();requestAnimationFrame(()=>$('#qa-input')?.focus());}
function renderQA(){qaMatches=QA.filter(a=>qaCategory==='전체'||a.category===qaCategory).map((a,i)=>({a,s:rank(qaQuery,a),i})).filter(r=>r.s>0).sort((a,b)=>b.s-a.s||a.i-b.i).map(r=>r.a);if(!qaMatches.some(a=>a.id===selectedAnswer))selectedAnswer=qaMatches[0]?.id||null;$('#qa-results').innerHTML=qaMatches.length?qaMatches.map(a=>`<button class="qa-result ${a.id===selectedAnswer?'active':''}" data-answer="${esc(a.id)}" aria-pressed="${a.id===selectedAnswer}"><small>${esc(a.category)}</small><strong>${esc(a.q)}</strong></button>`).join(''):'<p class="empty-results">수록된 질문에서 찾지 못했습니다.<br>핵심 단어로 다시 검색하거나<br>확인할 질문으로 남겨 주세요.</p>';renderAnswer();}
function renderAnswer(){const a=QA.find(a=>a.id===selectedAnswer);const root=$('#qa-answer');if(!a){root.innerHTML=`<div class="empty-answer"><div class="answer-label">NOT IN THE ANSWER BOOK</div><h3>여기서 지어내지 않겠습니다.</h3><p>이 질문에 대한 확인된 답변이 아직 수록되지 않았습니다. 질문과 확인할 항목을 남기고, 근거를 확보한 뒤 답하겠습니다.</p><div class="answer-tools"><button class="text-btn" id="record-unanswered">확인할 질문으로 기록 ${icon('note')}</button></div></div>`;return;}root.innerHTML=`<div class="answer-meta"><span>${esc(a.category)}</span><span>/</span><span>${esc(a.evidence)}</span></div><h3>${esc(a.q)}</h3><div class="answer-label">바로 답하기</div><p class="answer-short">${esc(a.short)}</p><div class="answer-detail"><div class="answer-label">더 깊이 답하기</div>${a.detail.map(p=>'<p>'+esc(p)+'</p>').join('')}</div><div class="answer-warning">${esc(a.caution)}</div>${a.url?'<a class="source-link" href="'+esc(a.url)+'" target="_blank" rel="noopener noreferrer">원저자 자료 확인 ↗</a>':''}<div class="answer-tools"><button class="text-btn" data-jump="${esc(a.slide)}">설명 장면으로 ${icon('right')}</button><button class="text-btn" data-copy-answer="${esc(a.id)}">답변 복사 ${icon('copy')}</button><button class="text-btn" data-note="${esc(a.q)}">후속 질문 기록 ${icon('note')}</button></div>`;root.scrollTop=0;$$('.qa-result').forEach(b=>{b.classList.toggle('active',b.dataset.answer===selectedAnswer);b.setAttribute('aria-pressed',String(b.dataset.answer===selectedAnswer));});}
function showMap(){openDialog('map',header('이야기의 전체 지도','질문에 맞는 장면을 열고, 하단의 “발표로 복귀”로 돌아오세요.')+`<div class="dialog-body"><div class="map-grid">${SLIDES.map((s,i)=>`<button class="map-card ${i===index?'current':''}" data-jump="${s.id}"><small>${String(i+1).padStart(2,'0')} / ${s.short?'핵심 경로':'심화 장면'}</small><h3>${esc(s.label)}</h3><span class="map-chapter">${esc(s.chapter)}</span></button>`).join('')}</div></div>`);}
function showHelp(){const rows=[['다음 / 이전 장면','→ / ←'],['다음 / 이전 장면','Space / Shift+Space'],['처음 / 마지막 장면','Home / End'],['질문 검색','Q / Ctrl+K'],['전체 장면','M'],['발표자 창','P'],['멘토링 기록','N'],['전체 화면','F'],['타이머 시작 / 정지','T'],['화면 가리기 / 복귀','B'],['답변·창 닫기','Esc'],['사용법','?']];openDialog('help',header('발표는 흐르게. 질문은 바로.','발표 화면과 질문 답변집을 오가는 키노트입니다.')+`<div class="dialog-body"><div class="help-grid">${rows.map(r=>`<div class="shortcut-row"><span>${r[0]}</span><span class="key" style="height:auto;padding:5px 8px">${r[1]}</span></div>`).join('')}</div><p class="notes-hint" style="margin-top:25px">질문 창에서는 ↑ / ↓로 답변을 선택하고 Enter로 본문으로 이동합니다. 휴대폰에서는 좌우 스와이프 또는 아래 화살표를 사용하세요. 발표자 창은 같은 브라우저에서 발표 화면과 연결됩니다. 화면 공유 시에는 발표 화면만 공유하세요.</p><div class="answer-tools"><button class="text-btn" data-open="notes">멘토링 기록</button><button class="text-btn" data-open="sources">자료 기준·한계</button><button class="text-btn" id="timer-reset">타이머 초기화</button></div></div>`);}
function getNotes(){try{const parsed=JSON.parse(localStorage.getItem(STORE)||'[]');if(Array.isArray(parsed))return parsed.filter(n=>n&&typeof n.id==='string'&&typeof n.title==='string'&&typeof n.text==='string').slice(-500);}catch{}return memoryNotes;}
function putNotes(notes){memoryNotes=notes;try{localStorage.setItem(STORE,JSON.stringify(notes));return true;}catch{notify('브라우저 저장이 제한되었습니다. 기록을 내보내 보관해 주세요.');return false;}}
function showNotes(prefill=''){openDialog('notes',header('질문을, 다음 행동으로.','메모는 이 브라우저에만 저장됩니다. 공유 기기에서는 사용 후 내보내기·삭제를 권장합니다.',`<button class="text-btn" id="export-notes">내보내기 ${icon('download')}</button>`)+`<div class="dialog-body"><form class="note-form" id="note-form"><label for="note-title">논의할 질문</label><input id="note-title" maxlength="300" value="${esc(prefill)}" placeholder="어떤 가정을 먼저 검증할까요?"><label for="note-text">멘토 의견 · 결정 사항 · 다음 행동</label><textarea id="note-text" maxlength="12000" placeholder="멘토 의견:\n결정 사항:\n다음 행동:"></textarea><div class="note-actions"><span class="notes-hint">현재 장면: ${esc(SLIDES[index].label)}</span><button type="submit" class="primary">기록 저장 ${icon('right')}</button></div></form><div class="note-list" id="note-list"></div></div>`);$('#note-form').addEventListener('submit',e=>{e.preventDefault();const title=$('#note-title').value.trim(),text=$('#note-text').value.trim();if(!title&&!text){notify('질문이나 메모를 먼저 입력해 주세요.');return;}const notes=getNotes();notes.push({id:unique(),title:title||'멘토링 메모',text:text||'확인 후 답변할 질문',slide:SLIDES[index].label,date:new Date().toISOString()});const stored=putNotes(notes.slice(-500));$('#note-title').value='';$('#note-text').value='';renderNotesList();if(stored)notify('이 브라우저에 기록했습니다.');});renderNotesList();requestAnimationFrame(()=>$(prefill?'#note-text':'#note-title')?.focus());}
function renderNotesList(){const notes=getNotes();if(!$('#note-list'))return;$('#export-notes').disabled=!notes.length;$('#note-list').innerHTML=notes.length?[...notes].reverse().map(n=>`<article class="saved-note"><small>${esc(new Date(n.date).toLocaleString('ko-KR'))} · ${esc(n.slide||'')}</small><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p><button data-delete-note="${esc(n.id)}">이 기록 삭제</button></article>`).join(''):'<p class="notes-hint" style="margin-top:20px">아직 기록이 없습니다. 질문을 모아 검증 계획으로 바꿔 보세요.</p>';}
function downloadNotes(){const notes=getNotes();if(!notes.length){notify('내보낼 기록이 없습니다.');return;}let text='# TRACE 멘토링 기록\n\n내보낸 시각: '+new Date().toLocaleString('ko-KR')+'\n\n';for(const n of notes)text+='## '+n.title.replace(/\n/g,' ')+'\n\n'+n.text+'\n\n장면: '+(n.slide||'')+'\n기록 시각: '+n.date+'\n\n---\n\n';const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='TRACE_멘토링_기록_'+new Date().toISOString().slice(0,10)+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);notify('멘토링 기록을 Markdown으로 내보냈습니다.');}
function showSources(){openDialog('sources',header('어디까지 확인했는가.','구현 보고 · 개발자 설명 · 개념 시연 · 검증 계획을 구분합니다.')+`<div class="dialog-body source-list">${SOURCES.map(s=>`<article><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p>${s.url?'<a class="source-link" href="'+esc(s.url)+'" target="_blank" rel="noopener noreferrer">원저자 자료 ↗</a>':''}</article>`).join('')}</div>`);}
async function copyAnswer(id){const a=QA.find(x=>x.id===id);if(!a)return;const text=a.q+'\n\n'+a.short+'\n\n'+a.detail.join('\n\n')+'\n\n주의: '+a.caution+'\n근거: '+a.evidence;try{await navigator.clipboard.writeText(text);notify('답변과 주의사항을 함께 복사했습니다.');}catch{const t=document.createElement('textarea');t.value=text;t.style.cssText='position:fixed;left:-9999px;top:0';$('#dialog').appendChild(t);t.select();try{const ok=document.execCommand('copy');notify(ok?'답변을 복사했습니다.':'이 브라우저에서는 복사가 제한됩니다. 답변 본문을 선택해 복사하세요.');}catch{notify('답변 본문을 선택해 복사해 주세요.');}t.remove();}}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else notify('이 브라우저는 전체 화면을 지원하지 않습니다. 가로 화면으로 사용해 주세요.');}catch{notify('전체 화면 전환이 제한되었습니다. 브라우저의 전체 화면 기능을 사용해 주세요.');}}
function openPresenter(){if(isPresenter)return;const url=new URL(location.href);url.searchParams.set('presenter','1');url.searchParams.set('session',session);const w=window.open(url.href,'TRACE_Presenter_'+session,'popup,width=1180,height=780');if(!w){notify('팝업이 차단되었습니다. 이 사이트의 팝업을 허용해 주세요.');return;}sendState();}
function renderPresenter(){const s=SLIDES[index];$('#p-position').textContent=String(index+1).padStart(2,'0')+' / '+SLIDES.length+' · '+s.chapter;$('#p-title').textContent=s.label;$('#p-script').textContent=s.notes;const route=path(),pos=route.indexOf(index),next=pos<0?route.find(n=>n>index):route[pos+1];$('#p-next').textContent=next===undefined?'발표 종료 · 질의응답으로 이어가세요.':SLIDES[next].label;const rel=QA.filter(a=>a.slide===s.id).slice(0,4);$('#p-related').innerHTML=rel.map(a=>`<button data-qa="${esc(a.id)}">${esc(a.q)} ${icon('right')}</button>`).join('');}
function show(type){if(type==='qa')showQA();else if(type==='map')showMap();else if(type==='help')showHelp();else if(type==='notes')showNotes();else if(type==='sources')showSources();}
document.addEventListener('click',e=>{const b=e.target.closest('button,a.brand');if(!b)return;if(b.matches('a.brand')){e.preventDefault();goTo(0);return;}if(b.dataset.open){show(b.dataset.open);return;}if(b.hasAttribute('data-close')){closeDialog();return;}if(b.dataset.qa){showQA(b.dataset.qa);return;}if(b.dataset.head){showQA('head-'+b.dataset.head);return;}if(b.hasAttribute('data-note')){showNotes(b.dataset.note);return;}if(b.dataset.scenario){updateScenario(b.dataset.scenario);return;}if(b.dataset.context){updateContext(b.dataset.context);return;}if(b.dataset.category){qaCategory=b.dataset.category;$$('[data-category]').forEach(x=>x.classList.toggle('active',x.dataset.category===qaCategory));selectedAnswer=null;renderQA();return;}if(b.dataset.answer){selectedAnswer=b.dataset.answer;renderAnswer();return;}if(b.dataset.jump){const n=SLIDES.findIndex(s=>s.id===b.dataset.jump);closeDialog();if(isPresenter)command('goto',n);else goTo(n,{detour:true});return;}if(b.hasAttribute('data-goto')){goTo(Number(b.dataset.goto));return;}if(b.dataset.copyAnswer){copyAnswer(b.dataset.copyAnswer);return;}if(b.dataset.deleteNote){if(confirm('이 멘토링 기록을 삭제할까요?')){putNotes(getNotes().filter(n=>n.id!==b.dataset.deleteNote));renderNotesList();}return;}if(b.dataset.command){command(b.dataset.command);return;}if(b.hasAttribute('data-next')){command('next');return;}switch(b.id){case'next':command('next');break;case'previous':command('previous');break;case'back-to-talk':returnToTalk();break;case'timer-toggle':command('timer');break;case'timer-reset':command('resetTimer');notify('타이머를 초기화했습니다.');break;case'presenter-open':openPresenter();break;case'fullscreen':fullscreen();break;case'export-notes':downloadNotes();break;case'record-unanswered':showNotes(qaQuery.trim()||'확인할 질문');break;}});
$('#overlay').addEventListener('click',e=>{if(e.target===$('#overlay'))closeDialog();});
$('#screen-cover').addEventListener('click',()=>toggleCover(false));
$('#mode').addEventListener('change',e=>{mode=e.target.value==='brief'?'brief':'full';if(mode==='brief'&&!briefPath.includes(index))goTo(briefPath.find(n=>n>=index)??briefPath.at(-1));else{renderRail();sendState();}});
document.addEventListener('keydown',e=>{if(e.isComposing)return;const typing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName)||document.activeElement?.isContentEditable;if(e.key==='Escape'){if(!$('#overlay').hidden){closeDialog();e.preventDefault();return;}if(covered){toggleCover(false);e.preventDefault();return;}return;}if(covered){if(e.code==='KeyB'||e.key==='Enter'||e.key===' '){e.preventDefault();toggleCover(false);}return;}if(!$('#overlay').hidden){if(e.key==='Tab'){const focusables=$$('button:not([disabled]),a[href],input,textarea,select,[tabindex="0"]',$('#dialog')).filter(x=>x.getClientRects().length);const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){last?.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first?.focus();e.preventDefault();}}if(modalType==='qa'&&['ArrowDown','ArrowUp'].includes(e.key)&&(!typing||document.activeElement.id==='qa-input')){if(qaMatches.length){e.preventDefault();let i=qaMatches.findIndex(a=>a.id===selectedAnswer);i=Math.max(0,Math.min(qaMatches.length-1,i+(e.key==='ArrowDown'?1:-1)));selectedAnswer=qaMatches[i].id;renderAnswer();$('[data-answer="'+selectedAnswer+'"]')?.scrollIntoView({block:'nearest'});}}if(modalType==='qa'&&e.key==='Enter'&&document.activeElement.id==='qa-input'){e.preventDefault();$('#qa-answer').focus();}return;}if((e.ctrlKey||e.metaKey)&&e.code==='KeyK'){e.preventDefault();showQA();return;}if(typing||e.ctrlKey||e.metaKey||e.altKey)return;if(['ArrowRight','ArrowDown','PageDown'].includes(e.key)||e.key===' '&&!e.shiftKey){e.preventDefault();command('next');}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)||e.key===' '&&e.shiftKey){e.preventDefault();command('previous');}else if(e.key==='Home'){e.preventDefault();command('goto',path()[0]);}else if(e.key==='End'){e.preventDefault();command('goto',path().at(-1));}else if(e.key==='?'||e.code==='KeyH'){e.preventDefault();showHelp();}else{const actions={KeyQ:()=>showQA(),KeyM:showMap,KeyN:showNotes,KeyP:openPresenter,KeyF:fullscreen,KeyT:()=>command('timer'),KeyB:()=>command('cover')};if(actions[e.code]){e.preventDefault();actions[e.code]();}}});
$('#stage-area').addEventListener('pointerdown',e=>{if(e.pointerType==='touch'&&!e.target.closest('button,a,input,textarea'))pointerStart={x:e.clientX,y:e.clientY,time:Date.now()};else pointerStart=null;},{passive:true});
$('#stage-area').addEventListener('pointerup',e=>{if(!pointerStart)return;const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.8&&Date.now()-pointerStart.time<800)command(dx<0?'next':'previous');pointerStart=null;},{passive:true});
$('#stage-area').addEventListener('pointercancel',()=>pointerStart=null,{passive:true});
$('#stage-area').addEventListener('wheel',e=>{if(!$('#overlay').hidden||e.ctrlKey||matchMedia('(max-width:650px) and (orientation:portrait)').matches)return;if(Math.abs(e.deltaY)<35||Date.now()-lastWheel<850)return;e.preventDefault();lastWheel=Date.now();command(e.deltaY>0?'next':'previous');},{passive:false});
window.addEventListener('resize',fit);window.addEventListener('hashchange',()=>{if(isPresenter)return;const id=location.hash.slice(1),n=SLIDES.findIndex(s=>s.id===id);if(n>=0&&n!==index)goTo(n,{hash:false});});
renderScenes();
let hashIndex=SLIDES.findIndex(s=>s.id===location.hash.slice(1));
if(isPresenter){document.body.classList.add('is-presenter');index=Math.max(0,hashIndex);renderPresenter();post({type:'request'});}else{goTo(Math.max(0,hashIndex),{initial:true});}
fit();updateClock();setInterval(updateClock,250);setInterval(()=>{if(isPresenter){if(Date.now()-lastSync>5000)post({type:'request'});}else sendState();},2000);
window.TRACE_KEYNOTE={version:'1.0.0',get slideCount(){return SLIDES.length;},get answerCount(){return QA.length;},get index(){return index;},get mode(){return mode;},get session(){return session;},goTo:n=>goTo(n),showQA,showMap,showNotes,showSources,closeDialog};
})();
